//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeBlacks.Tests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CodeCoverageComparisonTestResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CodeCoverageComparisonTestResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CodeBlacks.Tests.CodeCoverageComparisonTestResources", typeof(CodeCoverageComparisonTestResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html data-ng-app=&quot;coverageApp&quot;&gt;
        ///&lt;head&gt;
        ///&lt;meta charset=&quot;utf-8&quot; /&gt;
        ///&lt;title&gt;RestSharp.RestClient - Coverage Report&lt;/title&gt;
        ///&lt;link rel=&quot;stylesheet&quot; type=&quot;text/css&quot; href=&quot;report.css&quot; /&gt;
        ///&lt;/head&gt;&lt;body data-ng-controller=&quot;DetailViewCtrl&quot;&gt;&lt;div class=&quot;container&quot;&gt;
        ///&lt;h1&gt;Summary&lt;/h1&gt;
        ///&lt;table class=&quot;overview&quot;&gt;
        ///&lt;colgroup&gt;
        ///&lt;col style=&quot;width: 135px;&quot; /&gt;
        ///&lt;col /&gt;
        ///&lt;/colgroup&gt;
        ///&lt;tbody&gt;
        ///&lt;tr&gt;&lt;th&gt;Class:&lt;/th&gt;&lt;td&gt;RestSharp.RestClient&lt;/td&gt;&lt;/tr&gt;
        ///&lt;tr&gt;&lt;th&gt;Assembly:&lt;/th&gt;&lt;td&gt;RestSharp&lt;/td&gt;&lt;/tr&gt;
        ///&lt;tr&gt;&lt;th&gt;File(s):&lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RestSharp_RestClient_New {
            get {
                return ResourceManager.GetString("RestSharp_RestClient_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html data-ng-app=&quot;coverageApp&quot;&gt;
        ///&lt;head&gt;
        ///&lt;meta charset=&quot;utf-8&quot; /&gt;
        ///&lt;title&gt;RestSharp.RestClient - Coverage Report&lt;/title&gt;
        ///&lt;link rel=&quot;stylesheet&quot; type=&quot;text/css&quot; href=&quot;report.css&quot; /&gt;
        ///&lt;/head&gt;&lt;body data-ng-controller=&quot;DetailViewCtrl&quot;&gt;&lt;div class=&quot;container&quot;&gt;
        ///&lt;h1&gt;Summary&lt;/h1&gt;
        ///&lt;table class=&quot;overview&quot;&gt;
        ///&lt;colgroup&gt;
        ///&lt;col style=&quot;width: 135px;&quot; /&gt;
        ///&lt;col /&gt;
        ///&lt;/colgroup&gt;
        ///&lt;tbody&gt;
        ///&lt;tr&gt;&lt;th&gt;Class:&lt;/th&gt;&lt;td&gt;RestSharp.RestClient&lt;/td&gt;&lt;/tr&gt;
        ///&lt;tr&gt;&lt;th&gt;Assembly:&lt;/th&gt;&lt;td&gt;RestSharp&lt;/td&gt;&lt;/tr&gt;
        ///&lt;tr&gt;&lt;th&gt;File(s):&lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RestSharp_RestClient_Old {
            get {
                return ResourceManager.GetString("RestSharp_RestClient_Old", resourceCulture);
            }
        }
    }
}
